"""Convert Kerzoven's CC0 sleepy purr WAV into board-local 24 kHz mono PCM.

Run with Python 3.11 (stdlib audioop) and the downloaded source WAV as argument.
"""
import audioop
import hashlib
from pathlib import Path
import struct
import sys
import wave

source = Path(sys.argv[1])
with wave.open(str(source), "rb") as wav:
    pcm = wav.readframes(wav.getnframes())
    width, channels, rate = wav.getsampwidth(), wav.getnchannels(), wav.getframerate()
assert channels in (1, 2)
pcm = audioop.lin2lin(pcm, width, 2)
if channels == 2:
    pcm = audioop.tomono(pcm, 2, 0.5, 0.5)
pcm, _ = audioop.ratecv(pcm, 2, 1, rate, 24000, None)
samples = list(struct.unpack('<' + 'h' * (len(pcm) // 2), pcm))
# Blend the last 40 ms into the first 40 ms, avoiding a hard loop boundary.
n = 960
assert len(samples) > n * 2
blend = [round((samples[-n + i] * (n-i) + samples[i] * i) / n) for i in range(n)]
samples = blend + samples[n:-n]
dest = Path(__file__).resolve().parents[1] / 'main/boards/m5stack/stackchan-k151/purr_pcm.h'
with dest.open('w') as out:
    out.write('// Generated by tools/convert_purr.py. Kerzoven, CC0. See PURR_LICENSE.md.\n')
    out.write('// Source SHA256: ' + hashlib.sha256(source.read_bytes()).hexdigest() + '\n')
    out.write('#pragma once\n#include <cstdint>\nnamespace stackchan {\ninline constexpr int16_t kPurrPcm[] = {\n')
    for start in range(0, len(samples), 16):
        out.write('    ' + ', '.join(map(str, samples[start:start+16])) + ',\n')
    out.write('};\n}\n')
print(f'{len(samples)} samples, {len(samples)*2} bytes, {len(samples)/24000:.2f} seconds')
